/** Spec §19 public plane. Keep in lockstep with casops.api.control.SPEC_V3_PATHS. */
export const SPEC_V3_PATHS = [
  ["GET", "/api/v3/agents/{agent_id}/structure"],
  ["GET", "/api/v3/agents/{agent_id}/resolved"],
  ["POST", "/api/v3/agents/{agent_id}/compose-preview"],
  ["GET", "/api/v3/agents/{agent_id}/runtime/plan"],
  ["GET", "/api/v3/agents/{agent_id}/runtime/capabilities"],
  ["GET", "/api/v3/agents/{agent_id}/capabilities/matrix"],
  ["POST", "/api/v3/agents/{agent_id}/capabilities/verify"],
  ["GET", "/api/v3/agents/{agent_id}/runtime/context-budget"],
  ["GET", "/api/v3/agents/{agent_id}/cache/stats"],
  ["POST", "/api/v3/agents/{agent_id}/cache/invalidate"],
  ["GET", "/api/v3/agents/{agent_id}/protocols"],
  ["GET", "/api/v3/agents/{agent_id}/plugins"],
  ["POST", "/api/v3/agents/{agent_id}/plugins/validate"],
  ["GET", "/api/v3/agents/{agent_id}/memory/policy"],
  ["GET", "/api/v3/agents/{agent_id}/memory/hierarchy"],
  ["POST", "/api/v3/agents/{agent_id}/memory/query"],
  ["POST", "/api/v3/agents/{agent_id}/memory/write-candidate"],
  ["POST", "/api/v3/agents/{agent_id}/memory/consolidate"],
  ["DELETE", "/api/v3/agents/{agent_id}/memory/{memory_id}"],
  ["POST", "/api/v3/agents/{agent_id}/memory/{memory_id}/verify-deletion"],
  ["GET", "/api/v3/traces/{trace_id}"],
  ["POST", "/api/v3/traces/{trace_id}/replay"],
  ["GET", "/api/v3/traces/{trace_id}/root-cause"],
  ["GET", "/api/v3/artifacts/{artifact_id}/evidence-graph"],
  ["GET", "/api/v3/agents/{agent_id}/safety/incidents"],
  ["POST", "/api/v3/agents/{agent_id}/safety/redteam"],
  ["GET", "/api/v3/agents/{agent_id}/improvement/candidates"],
  ["POST", "/api/v3/agents/{agent_id}/improvement/candidates/{cid}/evaluate"],
  ["POST", "/api/v3/agents/{agent_id}/improvement/candidates/{cid}/approve"],
  ["POST", "/api/v3/agents/{agent_id}/improvement/rollback/{version}"],
  ["GET", "/api/v3/agents/{agent_id}/improvement/ledger"],
  ["GET", "/api/v3/agents/{agent_id}/regression/suite"],
  ["GET", "/api/v3/agents/{agent_id}/corrigibility/attestation"],
  ["GET", "/api/v3/agents/{agent_id}/validation/report"],
  ["POST", "/api/v3/agents/{agent_id}/runtime/run"],
] as const;

export const COMPANION_V3_PATHS = [
  ["GET", "/api/v3/agents"],
  ["GET", "/api/v3/llm/providers"],
  ["GET", "/api/v3/llm/settings"],
  ["POST", "/api/v3/llm/settings"],
  ["GET", "/api/v3/agents/{agent_id}/llm"],
  ["POST", "/api/v3/agents/{agent_id}/llm"],
  ["POST", "/api/v3/agents/{agent_id}/runtime/chat"],
  ["GET", "/api/v3/agents/{agent_id}/evals/fixtures"],
  ["GET", "/api/v3/agents/{agent_id}/files"],
  ["GET", "/api/v3/agents/{agent_id}/files/item"],
  ["PUT", "/api/v3/agents/{agent_id}/files/item"],
] as const;

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
export type SpecPath = (typeof SPEC_V3_PATHS)[number];

export const CLIENT_BINDINGS = {
  getStructure: ["GET", "/api/v3/agents/{agent_id}/structure"],
  getResolved: ["GET", "/api/v3/agents/{agent_id}/resolved"],
  composePreview: ["POST", "/api/v3/agents/{agent_id}/compose-preview"],
  getRuntimePlan: ["GET", "/api/v3/agents/{agent_id}/runtime/plan"],
  getRuntimeCapabilities: ["GET", "/api/v3/agents/{agent_id}/runtime/capabilities"],
  getCapabilitiesMatrix: ["GET", "/api/v3/agents/{agent_id}/capabilities/matrix"],
  verifyCapabilities: ["POST", "/api/v3/agents/{agent_id}/capabilities/verify"],
  getContextBudget: ["GET", "/api/v3/agents/{agent_id}/runtime/context-budget"],
  getCacheStats: ["GET", "/api/v3/agents/{agent_id}/cache/stats"],
  invalidateCache: ["POST", "/api/v3/agents/{agent_id}/cache/invalidate"],
  getProtocols: ["GET", "/api/v3/agents/{agent_id}/protocols"],
  getPlugins: ["GET", "/api/v3/agents/{agent_id}/plugins"],
  validatePlugins: ["POST", "/api/v3/agents/{agent_id}/plugins/validate"],
  getMemoryPolicy: ["GET", "/api/v3/agents/{agent_id}/memory/policy"],
  getMemoryHierarchy: ["GET", "/api/v3/agents/{agent_id}/memory/hierarchy"],
  queryMemory: ["POST", "/api/v3/agents/{agent_id}/memory/query"],
  writeMemoryCandidate: ["POST", "/api/v3/agents/{agent_id}/memory/write-candidate"],
  consolidateMemory: ["POST", "/api/v3/agents/{agent_id}/memory/consolidate"],
  deleteMemory: ["DELETE", "/api/v3/agents/{agent_id}/memory/{memory_id}"],
  verifyMemoryDeletion: ["POST", "/api/v3/agents/{agent_id}/memory/{memory_id}/verify-deletion"],
  getTrace: ["GET", "/api/v3/traces/{trace_id}"],
  replayTrace: ["POST", "/api/v3/traces/{trace_id}/replay"],
  getRootCause: ["GET", "/api/v3/traces/{trace_id}/root-cause"],
  getEvidenceGraph: ["GET", "/api/v3/artifacts/{artifact_id}/evidence-graph"],
  getIncidents: ["GET", "/api/v3/agents/{agent_id}/safety/incidents"],
  runRedteam: ["POST", "/api/v3/agents/{agent_id}/safety/redteam"],
  listCandidates: ["GET", "/api/v3/agents/{agent_id}/improvement/candidates"],
  evaluateCandidate: ["POST", "/api/v3/agents/{agent_id}/improvement/candidates/{cid}/evaluate"],
  approveCandidate: ["POST", "/api/v3/agents/{agent_id}/improvement/candidates/{cid}/approve"],
  rollback: ["POST", "/api/v3/agents/{agent_id}/improvement/rollback/{version}"],
  getLedger: ["GET", "/api/v3/agents/{agent_id}/improvement/ledger"],
  getRegressionSuite: ["GET", "/api/v3/agents/{agent_id}/regression/suite"],
  getAttestation: ["GET", "/api/v3/agents/{agent_id}/corrigibility/attestation"],
  getValidationReport: ["GET", "/api/v3/agents/{agent_id}/validation/report"],
  runAgent: ["POST", "/api/v3/agents/{agent_id}/runtime/run"],
  listAgents: ["GET", "/api/v3/agents"],
  listLlmProviders: ["GET", "/api/v3/llm/providers"],
  getLlmSettings: ["GET", "/api/v3/llm/settings"],
  setLlmSettings: ["POST", "/api/v3/llm/settings"],
  getAgentLlm: ["GET", "/api/v3/agents/{agent_id}/llm"],
  setAgentLlm: ["POST", "/api/v3/agents/{agent_id}/llm"],
  chatAgent: ["POST", "/api/v3/agents/{agent_id}/runtime/chat"],
  getEvalFixtures: ["GET", "/api/v3/agents/{agent_id}/evals/fixtures"],
  listAgentFiles: ["GET", "/api/v3/agents/{agent_id}/files"],
  getAgentFile: ["GET", "/api/v3/agents/{agent_id}/files/item"],
  putAgentFile: ["PUT", "/api/v3/agents/{agent_id}/files/item"],
} as const;

export const MUTATING = new Set<string>(["POST", "PUT", "PATCH", "DELETE"]);
export const LONG_TIMEOUT_MS = 120_000;
export const DEFAULT_TIMEOUT_MS = 30_000;
