"""Spec §20 codes and conditions. Do not add codes that are not in the specification."""

from __future__ import annotations

# code, category, condition, default_action
SPEC_ROWS: tuple[tuple[str, str, str, str], ...] = (
    ("INH_CYCLE", "inheritance", "Parent graph cycle", "Abort"),
    ("INH_PARENT_MISSING", "inheritance", "Parent folder or required file missing", "Abort"),
    ("INH_STRUCTURE_MISMATCH", "inheritance", "Incompatible family", "Abort"),
    ("INH_DEPTH", "inheritance", "Depth exceeds limit", "Abort"),
    ("INH_PARENT_LIMIT", "inheritance", "Parent limit exceeded", "Abort"),
    ("INH_SURFACE_UNKNOWN", "inheritance", "Unknown inherited surface", "Abort"),
    ("INH_SELF_PARENT", "inheritance", "Child names itself", "Abort"),
    ("INH_RESOLVED_DRIFT", "inheritance", "Generated resolution differs from source hashes", "Abort"),
    ("INH_FIXTURE_REMOVAL", "inheritance", "Fixture removed without waiver", "Abort"),
    ("SKL_TOGGLE_UNKNOWN", "skills", "Toggle targets unknown skill", "Abort"),
    ("SKL_MISSING_FILES", "skills", "Enabled skill lacks required files", "Abort"),
    ("SKL_TOOL_LEAK", "skills", "Skill attempts undeclared tool grant", "Abort"),
    ("IDN_NAMED_PERSON", "identity", "Named-person overlay lacks approval", "Abort"),
    ("IDN_LICENSE_CLAIM", "identity", "Persona asserts a real license", "Abort"),
    ("IDN_DISCLOSURE_MISSING", "identity", "Overlay lacks disclosure", "Abort"),
    ("GATE_NETWORK", "gate", "Inheritance or identity attempts network grant", "Abort"),
    ("GATE_ACTIVATION", "gate", "Agent attempts production activation", "Abort"),
    ("PERF_PLAN_CYCLE", "performance", "DAG cycle", "Abort"),
    ("PERF_UNSAFE_PARALLELISM", "performance", "Unsafe side-effect concurrency", "Abort"),
    ("PERF_BUDGET_EXCEEDED", "performance", "Compile-time budget infeasible", "Abort or escalate"),
    ("PERF_DEADLINE", "performance", "Deadline exceeded", "Cancel with bounded failure"),
    ("PERF_CACHE_SCOPE", "performance", "Cache crosses boundary", "Abort and purge"),
    ("PERF_ROUTE_UNAVAILABLE", "performance", "Route unavailable", "Approved fallback only"),
    ("PERF_STOP_RULE", "performance", "Stopping rule absent or unauditable", "Abort adaptive mode"),
    ("PERF_SPECULATION_COMMIT", "performance", "Speculation commits before guard", "Abort and compensate"),
    ("PERF_FALLBACK_INVALID", "performance", "Fallback lacks validation", "Containment stop"),
    ("CACHE_INVALIDATION", "cache", "Dependency not invalidated before read", "Disable tier and purge"),
    ("CACHE_EQUIVALENCE", "cache", "Cached and baseline semantics diverge", "Disable tier"),
    ("CACHE_SEMANTIC_REUSE", "cache", "T3 exceeds false-reuse threshold", "Disable T3"),
    ("CTX_PRESERVATION", "context", "Compaction loses invariant or critical constraint", "Escalate or stop"),
    ("CTX_BUDGET", "context", "Required pinned context exceeds budget", "Reject or split task"),
    ("CMP_PROTOCOL_VERSION", "compatibility", "Unsupported protocol revision", "Abort"),
    ("CMP_CAPABILITY_MISSING", "compatibility", "Required capability absent", "Abort"),
    ("CMP_ASSERTED_UNVERIFIED", "compatibility", "Production binding targets unverified capability", "Abort"),
    ("CMP_CAPABILITY_DRIFT", "compatibility", "Verified capability later fails", "Quarantine route"),
    ("CMP_SCHEMA_INCOMPATIBLE", "compatibility", "Schema major mismatch", "Abort"),
    ("CMP_TRACE_CONTEXT", "compatibility", "Trace/deadline/auth/taint lost", "Abort high-risk exchange"),
    ("CMP_SEMCONV_VERSION", "compatibility", "Semconv changes", "Quarantine export mapping"),
    ("CMP_TEMPLATE_DRIFT", "compatibility", "Template digest changes", "Re-run conformance"),
    ("CMP_TOKENIZER_DRIFT", "compatibility", "Tokenizer digest changes", "Re-run conformance"),
    ("CMP_JSON_SCHEMA_PROFILE", "compatibility", "Unsupported schema construct", "Fail compose"),
    ("OBS_TRACE_BROKEN", "observability", "Root or parent span missing", "Abort high-risk run"),
    ("OBS_REDACTION", "observability", "Content cannot be safely redacted", "Metadata only or abort"),
    ("OBS_COT_EXPORT", "observability", "Hidden reasoning targeted for export", "Block and alert"),
    ("OBS_AUDIT_UNAVAILABLE", "observability", "Exporter and local audit unavailable", "Containment stop"),
    ("OBS_SAMPLING_LOSS", "observability", "Mandatory trace category would be dropped", "Containment stop"),
    ("OBS_EVIDENCE_GRAPH", "observability", "Required graph missing or invalid", "Block artifact"),
    ("OBS_UNSUPPORTED_CLAIM", "observability", "Unsupported claim enters prohibited path", "Block write or artifact"),
    ("PLG_MANIFEST_INVALID", "plugins", "Invalid manifest", "Abort load"),
    ("PLG_SIGNATURE", "plugins", "Signature missing or invalid", "Abort load"),
    ("PLG_ABI", "plugins", "ABI incompatibility", "Abort load"),
    ("PLG_DEPENDENCY_CYCLE", "plugins", "Dependency cycle", "Abort load"),
    ("PLG_ISOLATION_TIER", "plugins", "Tier absent or too weak", "Abort load"),
    ("PLG_SBOM_MISSING", "plugins", "Production SBOM absent", "Abort load"),
    ("PLG_SUPPLY_CHAIN", "plugins", "Provenance unverifiable", "Abort load"),
    ("PLG_SCAN", "plugins", "Vulnerability threshold exceeded", "Abort load"),
    ("PLG_PERMISSION", "plugins", "Undeclared access", "Kill plugin and abort node"),
    ("PLG_HANDLE_FORGERY", "plugins", "Forged or unauthorized handle", "Kill plugin and alert"),
    ("PLG_HOT_SWAP", "plugins", "Replacement fails shadow validation", "Keep prior version"),
    ("MEM_PROVENANCE", "memory", "Write lacks valid provenance", "Quarantine"),
    ("MEM_SCOPE", "memory", "Tenant or subject mismatch", "Abort"),
    ("MEM_CONFLICT", "memory", "Irreconcilable memory conflict", "Abstain or escalate"),
    ("MEM_POISON", "memory", "Suspected malicious memory", "Quarantine"),
    ("MEM_TRUST_TIER", "memory", "Trust promotion violates policy", "Reject"),
    ("MEM_TAINT_LAUNDER", "memory", "Transform loses taint", "Reject output"),
    ("MEM_PAGE_LOSS", "memory", "Page-out loses retrievable state", "Abort"),
    ("MEM_DELETE_INCOMPLETE", "memory", "Derived copy remains", "Fail deletion SLA"),
    ("MEM_UNLEARN_VERIFY", "memory", "Post-deletion probe retrieves content", "Fail deletion SLA"),
    ("IMP_SCOPE", "improvement", "Candidate touches forbidden scope", "Reject and alert"),
    ("IMP_HOLDOUT_LEAK", "improvement", "Held-out leakage", "Reject"),
    ("IMP_REGRESSION", "improvement", "Release metric regression", "Reject or rollback"),
    ("IMP_UNSIGNED", "improvement", "Missing approved signature", "Reject"),
    ("IMP_SELF_APPROVAL", "improvement", "Self-promotion attempt", "Reject and alert"),
    ("IMP_ROLLBACK", "improvement", "Rollback absent or untested", "Block deployment"),
    ("IMP_REWARD_HACK", "improvement", "Reward-hacking detector fails", "Reject"),
    ("IMP_STAT_UNDERPOWERED", "improvement", "Power requirement not met", "Block promotion"),
    ("IMP_VERIFIER_MISSING", "improvement", "Objective lacks verifier", "Reject objective"),
    ("IMP_VERIFIER_DEPENDENCE", "improvement", "Verifier independence fails", "Reject"),
    ("IMP_CORRIGIBILITY", "corrigibility", "Invariant mismatch or attempted mutation", "Containment stop"),
    ("IMP_LEDGER_WRITE", "improvement", "Ledger integrity failure", "Block promotion"),
    ("SAF_INJECTION", "safety", "Injection detected", "Block affected instruction/action"),
    ("SAF_HIJACK", "safety", "Goal or tool hijack detected", "Block and incident"),
    ("SAF_EXFILTRATION", "safety", "Secret or PII egress attempt", "Block and incident"),
    ("SAF_TAINT", "safety", "Taint integrity failure", "Block"),
    ("SAF_TERMINATION", "safety", "Guard fails to halt correctly", "Containment stop"),
    ("SAF_EXTERNAL_EFFECT", "safety", "Unapproved external action", "Block and incident"),
    ("SAF_CASCADE", "safety", "Cross-agent escalation", "Halt exchange graph"),
    ("VAL_PLAN_DRIFT", "validation", "Analysis plan changes after run start", "Invalidate run"),
    ("VAL_FREEZE_DRIFT", "validation", "Frozen comparison input changes", "Invalidate comparison"),
    ("VAL_EXCLUSION", "validation", "Undeclared result exclusion", "Invalidate report"),
    ("CIT_UNVERIFIED", "citation", "Reference lacks accepted audit", "Block release"),
    ("CIT_MISMATCH", "citation", "Identifier/title/venue mismatch", "Delete or correct reference"),
    ("CIT_NUMERIC_CLAIM", "citation", "Numeric claim not located", "Withdraw claim"),
)
