"""ACP Chat prompt packing and echo stripping. Host-side; every agent_id."""

from __future__ import annotations

_SENTENCE_CONTINUE = set(" \n\r\t.,!?;:")
_PACK_NEEDLES = (
    "Host chat: treat the latest operator message as free-text input",
    "Enabled skills: (none enabled — do not load SKILL.md)",
    "Do not call tools, write memory, enable T3, or request network.",
    "GENERATED by project_grok_profile.py",
    "You are the composed CASOPS agent",
)


def pack_session_prompt(
    *,
    primed: bool,
    message: str,
    history: list[dict[str, str]],
) -> str:
    """User text for session/prompt. Packed system lives in profile.md, not here."""
    if primed or not history:
        return message
    parts: list[str] = ["## Conversation"]
    for turn in history:
        label = "Operator" if turn.get("role") == "user" else "Agent"
        parts.append(f"{label}: {turn.get('content', '')}")
    parts.append("## Operator message")
    parts.append(message)
    return "\n\n".join(parts)


def looks_like_packed_system(text: str) -> bool:
    head = (text or "")[:4000]
    if not head:
        return False
    if not any(needle in head for needle in _PACK_NEEDLES):
        return False
    return "Does not own:" in head or "## System" in head or "## Operator message" in head or "Voice:" in head


def strip_prompt_echo(prompt: str, reply: str) -> str:
    """If Grok completed the user prompt, keep only the continuation."""
    prompt_text = (prompt or "").strip()
    reply_text = reply or ""
    if not prompt_text or not reply_text:
        return reply_text
    body = reply_text.strip()
    if not body.startswith(prompt_text):
        return reply_text
    rest = body[len(prompt_text) :]
    packed = (
        len(prompt_text) >= 80
        or "## Operator message" in prompt_text
        or "## System" in prompt_text
        or looks_like_packed_system(prompt_text)
    )
    glued = bool(rest) and rest[0] not in _SENTENCE_CONTINUE
    if packed or glued:
        return rest.lstrip()
    return reply_text


def strip_chat_echo(*, prompt: str, reply: str, system: str = "", message: str = "") -> str:
    """Drop a leaked pack from Chat/ACP replies for any agent."""
    text = reply or ""
    if not text.strip():
        return text
    text = strip_prompt_echo(prompt, text)
    if (system or "").strip():
        text = strip_prompt_echo(system.strip(), text)
    text = _strip_operator_wrapper(text, message=(message or prompt or "").strip())
    return text


def _strip_operator_wrapper(reply: str, *, message: str) -> str:
    marker = "## Operator message"
    if marker not in reply:
        return reply
    lead = reply.lstrip()
    packish = (
        looks_like_packed_system(reply)
        or lead.startswith("## Operator message")
        or lead.startswith("## Conversation")
        or lead.startswith("## System")
    )
    if not packish:
        return reply
    after = reply.rsplit(marker, 1)[-1].lstrip("\n")
    if message and after.startswith(message):
        return after[len(message) :].lstrip()
    return after.lstrip()
